Remove the old building system, update READMEs and CI scripts.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,10 +1,6 @@
 sudo: required
 dist: xenial
 language: cpp
-# Could run both sets of kernels in parallel but setup is the majority of the time
-#env:
-#  - RTE_KERNELS=""
-#  - RTE_KERNELS="openacc"
 matrix:
   include:
   - compiler: gcc # Using
@@ -23,9 +19,8 @@ matrix:
   - compiler: gcc
     env:
     - FC=gfortran-9
-    - FCFLAGS="-ffree-line-length-none -m64 -std=f2003 -march=native -fbounds-check -finit-real=nan -DUSE_CBOOL"
+    - FCFLAGS="-ffree-line-length-none -m64 -std=f2003 -march=native -fbounds-check -finit-real=nan"
     - TEST_PGI=no
-    - NCHOME=/usr/
     addons:
       apt:
         sources:
@@ -37,9 +32,8 @@ matrix:
   - compiler: gcc
     env:
     - FC=gfortran-8
-    - FCFLAGS="-ffree-line-length-none -m64 -std=f2003 -march=native -fbounds-check -finit-real=nan -DUSE_CBOOL"
+    - FCFLAGS="-ffree-line-length-none -m64 -std=f2003 -march=native -fbounds-check -finit-real=nan"
     - TEST_PGI=no
-    - NCHOME=/usr/
     addons:
       apt:
         sources:
@@ -48,90 +42,57 @@ matrix:
           - gcc-8
           - gfortran-8
           - libnetcdf-dev
-# cache:
-#   timeout: 1000
-#   directories:
-#     - "$HOME/pgi/"
-before_install:
+install:
 # Install PGI Community edition if not present in cache
 - if [[ "${TEST_PGI}" == "yes" ]]; then
-  wget -q 'https://raw.githubusercontent.com/nemequ/pgi-travis/master/install-pgi.sh';
-  chmod +x install-pgi.sh;
-  ./install-pgi.sh --nvidia;
-  pgfortran --version;
-  echo "switch -pthread is" > .userrc;
-  echo "append(LDLIB1=-lpthread);" >> .userrc;
+    wget -q 'https://raw.githubusercontent.com/nemequ/pgi-travis/master/install-pgi.sh';
+    chmod +x install-pgi.sh;
+    ./install-pgi.sh --nvidia;
+    pgfortran --version;
+    echo "switch -pthread is" > .userrc;
+    echo "append(LDLIB1=-lpthread);" >> .userrc;
   fi
 
-# Install netcdf-fortran for PGI
-- git clone https://github.com/Unidata/netcdf-fortran.git --branch v4.4.4
-- cd netcdf-fortran
-- FC=$FC ./configure --prefix=${HOME}/netcdff
-- make
-- make install
-- cd .. || exit 1
+# Install netcdf-fortran (with default FCFLAGS)
+- git clone https://github.com/Unidata/netcdf-fortran.git --branch v4.4.4;
+  cd netcdf-fortran;
+  (unset FCFLAGS;
+   ./configure FC=$FC --prefix=${HOME}/netcdff && make && make install) || exit 1;
+  cd ..
 
 # Install CONDA
-- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
-- chmod +x miniconda.sh
-- ./miniconda.sh -b
-- export PATH=/home/travis/miniconda3/bin:$PATH
-- conda update --yes conda
+- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
+  chmod +x miniconda.sh;
+  ./miniconda.sh -b;
+  export PATH=/home/travis/miniconda3/bin:$PATH;
+  conda update --yes conda;
+  conda create --yes -n test
+  source activate test;
+  conda install --yes urllib3 netcdf4 xarray dask
 
-install:
-- conda create --yes -n test
-- source activate test
-- conda install --yes urllib3 netcdf4 xarray dask
-
-before_script:
-- export RRTMGP_ROOT=$PWD
-- export RRTMGP_DIR=$PWD/build
-- export NFHOME=${HOME}/netcdff
-- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NFHOME/lib
-- cd examples/rfmip-clear-sky
-- python3 ./stage_files.py
-- cd ../..
 script:
-# Build library - default kernels
-- cd build || exit 1
-- make || exit 1
-- cd .. || exit 1
-# Build and run RFMIP examples
-- cd examples/rfmip-clear-sky || exit 1
-- make clean
-- make || exit 1
-- python3 ./run-rfmip-examples.py
-- python3 ./compare-to-reference.py --fail=1.e-4
-- cd ../..
-# Build and run all-sky example
-- cd examples/all-sky || exit 1
-- make clean
-- make || exit 1
-- python3 ./run-allsky-example.py
-- python3 ./compare-to-reference.py
-- cd ../..
+# Build and check library - default kernels (also check in-source build)
+- ./configure --prefix=${HOME}/rte-rrtmgp --enable-tests --disable-openacc
+    --disable-silent-rules --with-netcdf-fortran=${HOME}/netcdff || { cat ./config.log; exit 1; }
+- make && make check && make install && make distclean
 #
-# Build library - Open-acc kernels
+# Build and check library - Open-acc kernels (also check out-of-source build)
 #
-- export RTE_KERNELS="openacc"
-- cd build || exit 1
-- make clean
-- make || exit 1
-- cd .. || exit 1
-# Build and run RFMIP examples
-- cd examples/rfmip-clear-sky || exit 1
-- make clean
-- make || exit 1
-- python3 ./run-rfmip-examples.py
-- python3 ./compare-to-reference.py --fail=1.e-4
-- cd ../..
-# Build and run all-sky example
-- cd examples/all-sky || exit 1
-- make clean
-- make || exit 1
-- python3 ./run-allsky-example.py
-- python3 ./compare-to-reference.py
-- cd ../..
+# PGI: we can simply enable OpenACC support.
+# GCC: both compilers support OpenACC 2.0 but we need OpenACC 2.6. Therefore,
+#      the compilation will fail because the configure script will automatically
+#      append '-fopenacc' to FCFLAGS. However, we still want to check OpenACC
+#      kernels but compile them without OpenACC support. A way to do that is to
+#      prevent the configure script from appending the flag by calling it with
+#      an additional argument 'acx_cv_fc_openacc_flag='.
+#
+- mkdir ./test_build && cd ./test_build
+- openacc_flag_arg=;
+  test x"$TEST_PGI" = xyes || openacc_flag_arg='acx_cv_fc_openacc_flag=';
+  echo "openacc_flag_arg='${openacc_flag_arg}'"
+- ../configure --prefix=${HOME}/rte-rrtmgp-openacc --enable-tests --enable-openacc ${openacc_flag_arg}
+    --disable-silent-rules --with-netcdf-fortran=${HOME}/netcdff || { cat ./config.log; exit 1; }
+- make && make check && make install && make distclean
 notifications:
   email:
     on_success: never
