CI: expect ifx+accel to fail

diff --git a/.github/workflows/containerized-ci.yml b/.github/workflows/containerized-ci.yml
--- a/.github/workflows/containerized-ci.yml
+++ b/.github/workflows/containerized-ci.yml
@@ -77,28 +77,51 @@ jobs:
         repository: earth-system-radiation/rrtmgp-data
         path: rrtmgp-data
     #
-    # Build libraries, examples and tests
+    # Build libraries, examples and tests (expect success)
     #
-    - name: Build libraries, examples and tests
+    - name: Build libraries, examples and tests (expect success)
+      id: build-success
+      if: matrix.fortran-compiler != 'ifx' || matrix.rte-kernels != 'accel'
       run: |
         $FC --version
         make libs
         make -C build separate-libs
     #
+    # Build libraries, examples and tests (expect failure)
+    #
+    - name: Build libraries, examples and tests (expect failure)
+      if: steps.build-success.outcome == 'skipped'
+      shell: bash
+      run: |
+        $FC --version
+        make libs 2> >(tee make.err >&2) && {
+          echo "Unexpected success"
+          exit 1
+        } || {
+          grep make.err -e 'Internal compiler error' && {
+            echo "Expected failure"
+          } || {
+            echo "Unexpected failure"
+            exit 1
+          }
+        }
+    #
     # Run examples and tests
     #
     - name: Run examples and tests
+      if: steps.build-success.outcome != 'skipped'
       run: make tests
     #
     # Relax failure thresholds for single precision
     #
     - name: Relax failure threshold for single precision
-      if: matrix.fpmodel == 'SP'
+      if: matrix.fpmodel == 'SP' && steps.build-success.outcome != 'skipped'
       run: echo "FAILURE_THRESHOLD=3.5e-1" >> $GITHUB_ENV
     #
     # Compare the results
     #
     - name: Compare the results
+      if: steps.build-success.outcome != 'skipped'
       run: make check
     #
     # Generate validation plots
