CI: expect cce-gpu-openmp to fail

diff --git a/.github/workflows/self-hosted-ci.yml b/.github/workflows/self-hosted-ci.yml
--- a/.github/workflows/self-hosted-ci.yml
+++ b/.github/workflows/self-hosted-ci.yml
@@ -103,18 +103,31 @@ jobs:
         make libs
         make -C build separate-libs
     #
-    # Run examples and tests
+    # Run examples and tests (expect success)
     #
-    - name: Run examples and tests
+    - name: Run examples and tests (expect success)
+      id: run-success
+      if: matrix.config-name != 'cce-gpu-openmp'
       run: make tests
+    #
+    # Run examples and tests (expect failure)
+    #
+    - name: Run examples and tests (expect failure)
+      if: steps.run-success.outcome == 'skipped'
+      run: |
+        make tests && {
+          echo "Unexpected success"
+          exit 1
+        } || echo "Expected failure"
     #
     # Relax failure thresholds for single precision
     #
     - name: Relax failure threshold for single precision
-      if: matrix.fpmodel == 'SP'
+      if: matrix.fpmodel == 'SP' && steps.run-success.outcome != 'skipped'
       run: echo "FAILURE_THRESHOLD=3.5e-1" >> $GITHUB_ENV
     #
     # Compare the results
     #
     - name: Compare the results
+      if: steps.run-success.outcome != 'skipped'
       run: make check
